[package]
name = "in2n"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal="0.13.5"
anyhow="1.0.53"
#pitch-detection="0.2.0"
rustfft="6.0.1"
